apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog-first
  namespace: projects
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: 63061/blog-first:v0.0.4
          ports:
          - containerPort: 3000
